import random
from datetime import datetime, timedelta

# ── Configuration ─────────────────────────────────────────────────────────────
N             = 100000000
ROWS_PER_FILE = 5000000
TABLE_NAME    = "sample"
OUTPUT_DIR    = f"/home/ubuntu/denischen/postgres-dbcomm/pg_scripts/data"
# ─────────────────────────────────────────────────────────────────────────────

FIRST_NAMES = ["Alice", "Bob", "Carol", "David", "Eve", "Frank", "Grace",
               "Hank", "Iris", "Jack", "Karen", "Leo", "Mia", "Nate", "Olivia"]
LAST_NAMES  = ["Smith", "Jones", "Williams", "Brown", "Taylor", "Wilson",
               "Davis", "Clark", "Hall", "Young", "King", "Scott", "Adams"]

def rand_name():
    return f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"

def rand_amount():
    return round(random.uniform(0.0, 99999.9999), 4)

def rand_date():
    start = datetime(2000, 1, 1)
    end   = datetime(2025, 12, 31)
    delta = end - start
    return (start + timedelta(days=random.randint(0, delta.days))).date()

def sq(val):
    return f"'{str(val).replace(chr(39), chr(39)*2)}'"

def build_row():
    values = [
        sq(rand_name()),
        str(rand_amount()),
        sq(rand_date()),
    ]
    return f"  ({', '.join(values)})"

def write_file(file_index, rows):
    output_file = f"{OUTPUT_DIR}/{TABLE_NAME}{file_index}.sql"
    row_block = ",\n".join(rows)
    insert = (
        f"INSERT INTO {TABLE_NAME} (name, amount, created_on) VALUES\n"
        f"{row_block};"
    )
    lines = [
        "-- Auto-generated by generate_rows.py",
        f"-- Rows: {len(rows)}  |  File: {file_index}  |  Generated: {datetime.now().isoformat()}",
        "",
        "BEGIN;",
        "",
        insert,
        "",
        "COMMIT;",
        "",
    ]
    with open(output_file, "w") as f:
        f.write("\n".join(lines))
    print(f"✓ Wrote {len(rows)} rows to '{output_file}'")

def main():
    file_index  = 0
    rows_buffer = []
    total_written = 0

    for i in range(N):
        rows_buffer.append(build_row())

        if len(rows_buffer) == ROWS_PER_FILE:
            write_file(file_index, rows_buffer)
            total_written += len(rows_buffer)
            file_index  += 1
            rows_buffer  = []

    # write any remaining rows
    if rows_buffer:
        write_file(file_index, rows_buffer)
        total_written += len(rows_buffer)

    print(f"✓ Done. {total_written} total rows across {file_index + 1} files.")

if __name__ == "__main__":
    main()